import Head from "next/head";
import { useMoralis } from "react-moralis";

export default function Home() {
  const { authenticate, logout, isAuthenticating, user, isAuthenticated } =
    useMoralis();
  if (!isAuthenticated) {
    return (
      <div className='main'>
        <button onClick={authenticate}>Login</button>
        {isAuthenticating && <p>Loading...</p>}
      </div>
    );
  }
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='main'>
        <h1>Hello 👋</h1>
        <h1>{user.get("ethAddress")}</h1>
        <button onClick={logout}>Logout</button>
      </main>
    </div>
  );
}
